Repository TECLIB/CFPropertyList, pull requests merged in 2018-04, with the labels that each got.

#48 Allow saveXML() to create formatted XML output
  src/CFPropertyList/CFPropertyList.php
Labels: feature

#50 test examples
  .travis.yml
Labels: test

#47 Code style
  .travis.yml
  composer.json
  src/CFPropertyList/CFArray.php
  src/CFPropertyList/CFBinaryPropertyList.php
  src/CFPropertyList/CFBoolean.php
  src/CFPropertyList/CFData.php
  src/CFPropertyList/CFDate.php
  src/CFPropertyList/CFDictionary.php
  src/CFPropertyList/CFNumber.php
  src/CFPropertyList/CFPropertyList.php
  src/CFPropertyList/CFString.php
  src/CFPropertyList/CFType.php
  src/CFPropertyList/CFTypeDetector.php
  src/CFPropertyList/CFUid.php
  src/CFPropertyList/IOException.php
  src/CFPropertyList/PListException.php
  tests/BinaryParseTest.php
  tests/EmptyElementsTest.php
  tests/ParseXMLTest.php
  tests/WriteBinaryTest.php
  tests/WriteXMLTest.php
  tests/bootstrap.php
Labels: style

#52 Fix html-proofer test
  _includes/head.html
Labels: test

#54 Add symmetry to CFDate encoding/decoding
  src/CFPropertyList/CFDate.php
Labels: bug

#56 Reverse the symmetry issue
  src/CFPropertyList/CFDate.php
  src/CFPropertyList/CFTypeDetector.php
Labels: bug
